# Plugins
gems:
- jekyll-sitemap
- jekyll-redirect-from
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude:
  - '/automation/'
  - 'README.md'
  - 'LICENSE.txt'
  - 'CNAME'
  # Temporary disabled pages
  - 'hackathon.it.html'
  - 'hackathon.en.html'
  - 'schedule.it.html'
  - 'schedule.en.html'
  - 'speakers.it.html'
  - 'speakers.en.html'
  - 'team.it.html'
  - 'team.en.html'

# Site Settings
title: "PGDay.IT 2017"
email: "pgday@itpug.org"
description:
  it: "Il PostgreSQL Day italiano è la giornata nazionale dedicata interamente a PostgreSQL, il più avanzato database Open Source al mondo"
  en: "The Italian PostgreSQL is the national day completely dedicated at PostgreSQL, the most advance open source database in the world"
baseurl: ""
url: "http://2017.pgday.it"
permalink: "/it/blog/:title"
googleAnalyticsTrackingId: "UA-99990720-1"
googleAnalyticsSiteUrl: "auto"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "ITPUG"
organizerAlternateName: "ITalian PostgreSQL Users Group"
organizerDescription: "ITPUG - Italian PostgreSQL Users Group è una associazione no-profit per la promozione, divulgazione e la tutela del Software Libero (FLOSS) in Italia.

In modo particolare, l'associazione ITPUG promuove l'adozione  di PostgreSQL (http://www.postgresql.org), uno dei progetti open source di maggior successo."
organizerEmail: "info@itpug.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.itpug.org/index.it.html"

# TODO: sistemare foto
# Head
metaKeywords: "event, PostgreSQL, Open Source, Disaster Recovery, programming, Big Data, Postgres, developers"
twitterAccount: "@PGDayIT"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/0JUVQUM0YPUt7UF53"
c4sponsorsUrl: "/assets/Diventa_Partner_IT_PGDay_2017.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speaker"}
# - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistica", lang: "it"}
 - {permalink: "/logistics/", text: "Logistics", lang: "en"}
 - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Diventa Speaker", lang: "it"}
 - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Become Speaker", lang: "en"}
 - {link: "/assets/Diventa_Partner_IT_PGDay_2017.pdf", text: "Diventa Partner", lang: "it"}
 - {link: "/assets/Be_Partner_EN_PGDay_2017.pdf", text: "Become Partner", lang: "en"}
 - {link: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231", text: "Acquista il tuo biglietto", lang: "it"}
 - {link: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231", text: "Buy your ticket", lang: "en"}
#bottomNavigationLinks:
# - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Diventa Speaker", lang: "it"}
# - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Become Speaker", lang: "en"}
# - {link: "/assets/Diventa_Partner_IT_PGDay_2017.pdf", text: "Diventa Partner", lang: "it"}
# - {link: "/assets/Be_Partner_EN_PGDay_2017.pdf", text: "Become Partner", lang: "en"}
#rightNavigationButtons:
# - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Diventa Speaker", lang: "it"}
# - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Become Speaker", lang: "en"}
# - {link: "/assets/Diventa_Partner_IT_PGDay_2017.pdf", text: "Diventa Partner", lang: "it"}
# - {link: "/assets/Be_Partner_EN_PGDay_2017.pdf", text: "Become Partner", lang: "en"}

# Hero Block
heroImage: "hero.jpg"
heroTitle:
  it: "PGDay.IT 2017 - <typeout> "
  en: "PGDay.IT 2017 - <typeout> "
eventDate:
  it: "Milano, 13 Ottobre, 2017"
  en: "Milan, October 13th, 2017"
typeoutTextValues:
  it: '"", "13 ottobre", "Milano", "Italy", ""'
  en: '"", "October 13th", "Milan", "Italy", ""'
typeoutFallback:
  it: "Milano, 13 ottobre 2017"
  en: "Milan, October 13th, 2017"
heroButtons:
 - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Diventa Speaker", lang: "it"}
 - {link: "https://goo.gl/forms/0JUVQUM0YPUt7UF53", text: "Become Speaker", lang: "en"}
 - {link: "/assets/Diventa_Partner_IT_PGDay_2017.pdf", text: "Diventa Partner", lang: "it"}
 - {link: "/assets/Be_Partner_EN_PGDay_2017.pdf", text: "Become Partner", lang: "en"}
 - {link: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231", text: "Acquista il tuo biglietto", lang: "it"}
 - {link: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231", text: "Get your ticket", lang: "en"}

# About Block
aboutTitle:
  it: "Informazioni sul PGDay.IT"
  en: "About PGDay.IT"
aboutBlock:
 - {lang: "it", title: "Conferenza", image: "conference.jpg", text: "PGDay.IT è la conferenza italiana dedicata a PostgreSQL, uno dei progetti open-source di maggior successo. Il primo PGDay.IT si è svolto il 7 luglio 2007 e da allora la manifestazione ha avuto una cadenza annuale. Questa è l'undicesima edizione." }
 - {lang: "en", title: "Conference", image: "conference.jpg", text: "PGDay.IT is the Italian event dedicated to PostgreSQL, one of the most successful open-source projects. The first PGDay.IT took place on July 7, 2007 and since then the event has had an annual cadence. This is the eleventh edition." }
 - {lang: "it", title: "Be social", image: "workshop.jpg", text: "Come nostro costume: l'immancabile PG_beer! Sei disposto a rinunciarci? Ancora non possiamo dirti dove avrà luogo, ma, seguendoci sui nostri canali, lo scoprirai presto." }
 - {lang: "en", title: "Be social", image: "workshop.jpg", text: "As our costume: the inevitable PG_beer! Are you willing to give up? We still cannot tell you where it will be, but following us on our channels, you will soon find out." }

# Statistic Block
statisticBlockTitle: "Dieci edizioni del PGDay.It:"
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "1257", specialCharacter: "+", info: "partecipanti", detail: "da tutta Europa"}
 - {count: "166", specialCharacter: "+", info: "ore", detail: "di puro PostgreSQL"}
 - {count: "158", specialCharacter: "+", info: "speaker", detail: "da tutto il mondo"}
 - {count: "22", specialCharacter: "", info: "track", detail: "oltre agli eventi sociali"}

# Latest News Block
latestNewsTitle:
  it: "Notizie dell'ultima ora"
  en: "Latest News"

# TODO: risulta vuota, può essere lasciata
# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speaker"
rockstarSpeakersButtonText: "Guarda tutti gli speaker"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Fondazione Stelline"
eventLocationLink: "http://www.stelline.it/it/centro-congressi/home/centro-congressi.html"
eventStreetAddress: "corso Magenta, 61"
eventAddressLocality: "Milano"
eventAddressLocalityRegion: "(MI)"
eventPostalCode: "20123"
eventAddressCountry: "Italy"
eventStartTime: "2017-10-13T9:00"
eventDoorTime: "08:30"
eventEndTime: "2017-10-13T18:00"
eventPlaceCoordinates: "45.4654533, 9.166099"
mapCenterCoordinates: "45.4654533, 9.166099"
mapMobileCenterCoordinates: "45.4654533, 9.166099"

# Venue Block
venueBlockTitle: "Location"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Fondazione Stelline"
venueFeatures: ["Nel cuore di Milano, di fronte al Cenacolo di Leonardo e a Santa Maria delle Grazie", "8.000 mq di superficie, 20 sale e meeting & training room"]

# TODO: sistemare url
# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "PGDayIT"
twitterFeed: "https://twitter.com/search?q=%23PGDayIT&src=typd=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizzatori"
partnersTitle: "Partner"
partnersC4sponsorsButton: "Diventa Partner"

# TODO: sistemare URL
# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Resta aggiornato"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Sarà possibile acquistare i biglietti a partire da metà giugno. Il numero dei biglietti disponibili è limitato. Rimanete sintonizzati!"

# Tickets Block
ticketsTitle: "Prezzo biglietti"
ticketsInfo: "Il biglietto vi garantirà l'accesso alla conferenza, ai coffee break ed al pranzo, incluse tutte le attività programmate per la giornata del 13 ottobre 2017. Nel prezzo del biglietto NON è incluso il pernottamento e NON sono inclusi gli eventi sociali come la pg_beer."
ticketsOffers:
 -
  name: "Early Bird"
  price: "47,00"
  priceCurrency: "€"
  buyButtonLink: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231"
  buyButtonText: "Acquistalo adesso"
  ticketContentList: ["Early Bird - PGDay.IT 2017", "13 ottobre", "Milano"]
  validFrom: "2017-06-15T10:00"
  validThrough: "2017-09-15T23:59"
  disabled: false
 -
  name: "Ordinario"
  price: "95,00"
  priceCurrency: "€"
  featured: true
  buyButtonLink: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231"
  buyButtonText: "Acquistalo adesso"
  ticketContentList: ["Ordinario - PGDay.IT 2017", "13 ottobre", "Milano"]
  validFrom: "2017-09-16T00:00"
  validThrough: "2017-10-12T23:59"
  disabled: true
 -
  name: "Studente"
  price: "15,00"
  priceCurrency: "€"
  buyButtonLink: "https://www.eventbrite.it/e/pgdayit-2017-tickets-35260542231"
  buyButtonText: "Acquistalo adesso"
  additionalInfo: "Sarà richiesto una dimostrazione di stato STUDENTE al desk della manifestazione. In assenza di dimostrazione, il biglietto sarà cancellato senza possibilità di rimborso."
  ticketContentList: ["Studente - PGDay.IT 2017", "13 ottobre", "Milano"]
  validFrom: "2017-06-15T10:00"
  validThrough: "2017-10-12T23:59"
  disabled: false

# TODO: sistemare permalink o cancellarlo
# Footer
socialLinks:
 - {link: "https://plus.google.com/114060631874544975126", icon: "google-plus"}
 - {link: "https://twitter.com/PGDayIT", icon: "twitter"}
 - {link: "https://www.facebook.com/ITPUG/", icon: "facebook"}
 - {link: "https://www.linkedin.com/company/itpug", icon: "linkedin"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.itpug.org", text: "ITPUG"}
 -
  lang: "it"
  title: "Contatti"
  links:
   - {link: "mailto:info@itpug.org", text: "info@itpug.org"}
 -
  lang: "en"
  title: "Contacts"
  links:
   - {link: "mailto:info@itpug.org", text: "info@itpug.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Codice di condotta", lang: "it"}
   - {permalink: "/cod/", text: "Code of conduct", lang: "en"}

# Blog
blogTitle:
  it: "Notizie dell'ultima ora"
  en: "Latest News"
blogReadMore:
  it: "continua a leggere"
  en: "read more"
blogCommentsEnabled: true
discusShortName: "PGDay.IT_2017"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "A proposito di ITPUG"
aboutUs: "ITPUG - Italian PostgreSQL Users Group è una associazione no-profit per la promozione, divulgazione e la tutela del Software Libero (FLOSS) in Italia. In modo particolare, l'associazione ITPUG promuove l'adozione  di PostgreSQL (http://www.postgresql.org), uno dei progetti open source di maggior successo. L'associazione è nata a Prato (PO) il 17 novembre 2007, poco dopo la prima edizione del PGDay.IT. Per maggiori informazioni sull'associazione ITPUG scrivi a info@itpug.org."

# Logistics Find Way Block
findWayTitle:
  it: "Trova la tua strada qui"
  en: "Find your way here"
findWayDestination:
  it: "al PGDay.IT"
  en: "to PGDay.IT"
findWayDistance:
  it: "Distanza"
  en: "Distance"
findWayDriving:
  it: "Con l'auto"
  en: "By car"
findWayWalking:
  it: "A piedi"
  en: "Walking"
findWayTransit:
  it: "Mezzi pubblici"
  en: "Public Transport"
findWayFindFlight:
  it: "Find Flight"
  en: "Find Flight"
viewOnMap:
  it: "Vedi su Google Maps"
  en: "View on Google Maps"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Come raggiungere il PGDay.IT 2017"
directionDetailsCards:
 - {lang: "it", title: "Arrivi in aereo su Linate?", information: 'Prendete il bus 73 in partenza dal piazzale dell’aeroporto e scendete al capolinea, in piazza San Babila; prendete la metropolitana MM1 in direzione Fiera/Rho, scendete alla fermata Cadorna Triennale, dirigetevi in piazza Cadorna, imboccate via Carducci e proseguite fino al primo semaforo incrociando corso Magenta, la Fondazione Stelline vi attende al civico 61.'}
 - {lang: "en", title: "Do you land at Linate Airport?", information: 'Take bus 73 departing from the piazza of the airport and exit at the end of the line, in piazza San Babila; take the Metropolitana MM1 in the direction of Fiera/Rho, exit to the stop for Cadorna Triennale, turn into piazza Cadorna, turn into via Carducci and continue to the first traffic light, crossing corso Magenta, Fondazione Stelline awaits you at number 61.'}

 - {lang: "it", title: "Arrivi in aereo su Malpensa?", information: 'Prendete il treno navetta “Malpensa Express” e raggiungete il capolinea a Milano Cadorna, dirigetevi in piazza Cadorna, imboccate via Carducci e proseguite fino al primo semaforo incrociando corso Magenta, la Fondazione Stelline vi attende al civico 61.'}
 - {lang: "en", title: "Do you land at Malpensa Airport??", information: 'Take shuttle train “Malpensa Express” and reach the head of the line at Milano Cadorna, turn into piazza Cadorna, turn into via Carducci and continue to the first traffic light, crossing corso Magenta, Fondazione Stelline awaits you at number 61.'}

 - {lang: "it", title: "Arrivi in treno?", information: 'Arrivati alla Stazione Centrale di Milano, o alla stazione Porta Garibaldi, prendete la metropolitana MM2 in direzione di Abbiategrasso e scendete alla fermata Cadorna Triennale, dirigetevi in piazza Cadorna, imboccate via Carducci e proseguite fino al primo semaforo incrociando corso Magenta, la Fondazione Stelline vi attende al civico 61.'}
 - {lang: "en", title: "Are you coming by train?", information: 'Arriving at the Central Station of Milan, or at the station Porta Garibaldi, take the Metropolitana MM2 in the direction of Abbiategrasso and exit to the stop for Cadorna Triennale, turn into piazza Cadorna, turn into via Carducci and continue to the first traffic light, crossing corso Magenta, Fondazione Stelline awaits you at number 61.'}

 - {lang: "it", title: "Arrivi in auto dalle autostrade del nord?", information: '(A4 Torino/Venezia; A9 Como/Chiasso; A8 Varese), dopo il casello del pedaggio proseguite in direzione Milano e prendete l’uscita Milano Certosa, percorrete tutto viale Certosa, attraversate due incroci e confluite in corso Sempione, alla fine del corso svoltate a destra per via Canova, alla fine della via girate a destra in via Pagano, dopo 200 m svoltate a sinistra in via Monti fino a raggiungere l’incrocio con corso Magenta, girate a destra e raggiungete il civico 61 dove vi attende la Fondazione Stelline.'}
 - {lang: "en", title: "Are you coming by car from the northern highway?", information: '(A4 Torino/Venezia; A9 Como/Chiasso; A8 Varese), after the tollbooth, continue in the direction of Milan and take the exit Milano Certosa, go to the end of viale Certosa, cross two crossings and merge into corso Sempione, at the end of the corso turn right on via Canova, at the end of the via turn right in via Pagano, after 200 m turn left in via Monti until reaching the crossing with corso Magenta, turn right and reach number 61, where you are welcomed to Fondazione Stelline.'}

 - {lang: "it", title: "Arrivi in auto dall’autostrada A1?", information: '(Bologna), dopo il casello del pedaggio, dirigendoVi verso la tangenziale Est, imboccate l’uscita di piazzale Corvetto, girate a destra e arrivate a piazzale Bologna, svoltate a sinistra per via Bacchiglione percorrete 100 m e girate a destra per corso Lodi. Dopo 700 m, giunti a porta Romana, girate a sinistra in via Filippetti (circonvallazione interna), proseguire per viale Beatrice d’Este, viale Gian Galeazzo, viale d’Annunzio, viale Papiniano, viale di Porta Vercellina. Arrivati a piazzale Baracca, proseguite per piazza della Conciliazione, svoltate a destra in via Boccaccio quindi percorrete la via fino a raggiungere piazza Virgilio. Dopodichè percorrete via Vincenzo Monti, al semaforo svoltate a destra in Largo d’Ancona e subito a destra in corso Magenta dove, al civico 61, vi attende la Fondazione Stelline.'}
 - {lang: "en", title: "Are you coming by car from highway A1?", information: '(Bologna), after the tollbooth, turn into the exit of piazzale Corvetto, turn right and you will arrive at piazzale Bologna, turn left through via Bacchiglione continue 100 m and turn right on corso Lodi. After 700 m, reaching porta Romana, turn left on via Filippetti (inner beltway), continue along viale Beatrice d’Este, viale Gian Galeazzo, viale d’Annunzio, viale Papiniano, viale of Porta Vercellina, arriving at piazzale Baracca, turn right, where at number 61 you are welcomed to Fondazione Stelline.'}

 - {lang: "it", title: "Arrivi in auto dall’autostrada A7?", information: '(Genova): dopo il casello del pedaggio, imboccate la tangenziale ovest in direzione Venezia, uscite a Milano Certosa e proseguite come indicato sopra.'}
 - {lang: "en", title: "Are you coming by car from highway A7?", information: '(Genova): after the tollbooth, turn into the western tangential in the direction of Venice, exit at Milano Certosa and continue as indicated above.'}
directionDetailsWideCards:
 -
  lang: "it"
  title: "Cerchi un hotel?"
  subCards:
   -
    title: "A Milano gli hotel non mancano. La location prescelta per il PGDay.2017 fornisce anche la possibilità di pernottare: 'Hotel Palazzo delle Stelline'. Alternative? Sotto ne trovi segnalate alcune nelle vicinanze della location del PGDay.IT 2017."
    links:
     - {link: "http://www.hotelpalazzostelline.it/", text: "Hotel Palazzo delle Stelline"}
     - {link: "http://www.anticalocandaleonardo.com/it/", text: "Antica Locanda Leonardo"}
     - {link: "http://www.hotel-bb.com/it/hotel/milano-sant-ambrogio.htm", text: "B&B Hotel Milano Sant'Ambrogio"}
     - {link: "http://www.hotelpanizza.it/", text: "Hotel Panizza"}
 -
  lang: "en"
  title: "Are you looking for an hotel"
  subCards:
   -
    title: "Hotels are not lacking in Milan. PGDay.IT venue also provides accomodations (Hotel Palazzo delle Stelline). Alternatives? Below you will find some others option close to PGDay.IT 2017."
    links:
     - {link: "http://www.hotelpalazzostelline.it/en", text: "Hotel Palazzo delle Stelline"}
     - {link: "http://www.anticalocandaleonardo.com", text: "Antica Locanda Leonardo"}
     - {link: "http://www.hotel-bb.com/it/hotel/milano-sant-ambrogio.htm", text: "B&B Hotel Milano Sant'Ambrogio"}
     - {link: "http://www.hotelpanizza.it/", text: "Hotel Panizza"}
